/**
 * Dev-time refresh of the vendored wiki snapshot under `vendor/stoneshard-wiki/`.
 *
 * Fetches the official wiki's raw item datastrings (Weapon data, Armor data) via
 * the MediaWiki `?action=raw` endpoint, records exact provenance (the page's
 * current revision id + timestamp from `Special:Export`), sanity-parses each blob
 * so a malformed fetch fails before it is written, and writes the raw files plus
 * a checksum manifest. Builds and CI never run this — they read the committed
 * snapshot (KTD3). Re-run per patch when the wiki refreshes.
 *
 * Run with: `npm run vendor:wiki` (or `tsx tools/wiki-extractor/fetch.ts`).
 * Output is committed. Network required; not runnable in CI.
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseDatastring } from '../../src/lib/data/wiki-datastring'
import { sha256 } from '../../scripts/checksum'
import { WIKI_PAGES } from '../../src/lib/data/wiki-pages'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const outDir = resolve(root, 'vendor/stoneshard-wiki')

const UA = 'StoneshardBuildCalculator/0.1 (data extraction; https://github.com/AntoKrator)'
const GAME_VERSION = '0.9.4.x'

async function get(url: string): Promise<string> {
  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`GET ${url} → HTTP ${res.status}`)
  return res.text()
}

/** Current revision id + timestamp via Special:Export (the API endpoint is off). */
async function provenance(title: string): Promise<{ revisionId: number; timestamp: string }> {
  const xml = await get(`https://stoneshard.com/wiki/Special:Export/${encodeURI(title)}`)
  const m = /<revision>[\s\S]*?<id>(\d+)<\/id>[\s\S]*?<timestamp>([^<]+)<\/timestamp>/.exec(xml)
  if (!m) throw new Error(`Could not read revision id for "${title}" from Special:Export`)
  return { revisionId: Number(m[1]), timestamp: m[2] }
}

const pages: Record<string, unknown> = {}
for (const page of WIKI_PAGES) {
  const url = `https://stoneshard.com/wiki/${encodeURI(page.title)}?action=raw`
  const wikitext = await get(url)
  // Fail before writing if the blob no longer parses (e.g. column drift).
  const { header, rows } = parseDatastring(wikitext, { leadingColumns: page.leadingColumns })
  const { revisionId, timestamp } = await provenance(page.title)

  mkdirSync(outDir, { recursive: true })
  writeFileSync(resolve(outDir, page.file), wikitext)
  pages[page.file] = {
    title: page.title,
    sourceUrl: url,
    revisionId,
    revisionTimestamp: timestamp,
    columns: header.length,
    sha256: sha256(wikitext),
  }
  console.log(`✓ ${page.title}: ${rows.length} rows, ${header.length} cols, rev ${revisionId}`)
}

const manifest = {
  source: 'stoneshard.com/wiki',
  retrievedAt: new Date().toISOString().slice(0, 10),
  gameVersion: GAME_VERSION,
  note: 'Vendored raw datastrings for `npm run transform-items` (network-independent). Generated by the official wiki parser from the game files, fetched via `?action=raw`. Game data is Ink Stains Games IP under fair use — see /NOTICE.md. Refresh with `tools/wiki-extractor/`.',
  pages,
}
writeFileSync(resolve(outDir, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n')
console.log(`Wrote ${Object.keys(pages).length} files + manifest → vendor/stoneshard-wiki/`)
